export const landingText = {
    vi: {
        brandName: 'Mầm Non Nắng Hồng',
        slogan: 'Nơi bé học vui mỗi ngày',
        navHome: 'Trang chủ',
        navAbout: 'Giới thiệu',
        navPrograms: 'Chương trình',
        navNews: 'Tin tức',
        navContact: 'Liên hệ',
        applyNow: 'Đăng ký ngay',
        loadError: 'Không tải được dữ liệu trang chủ',
        subscribeSuccessSummary: 'Đăng ký thành công',
        subscribeSuccessDetail: 'Cảm ơn bạn đã theo dõi Mầm Non Nắng Hồng',
        errorSummary: 'Lỗi',
        subscribeError: 'Không thể đăng ký newsletter',
        applyMissingSummary: 'Thiếu thông tin',
        applyMissingDetail: 'Vui lòng nhập tên phụ huynh, số điện thoại và tên bé',
        applyMissingProgramSummary: 'Thiếu chương trình',
        applyMissingProgramDetail: 'Vui lòng chọn chương trình cho bé',
        applySuccessSummary: 'Đăng ký thành công',
        applySuccessDetail: 'Nhà trường sẽ liên hệ phụ huynh trong thời gian sớm nhất',
        applyError: 'Không thể gửi thông tin đăng ký',
        fallbackProgramTitle1: 'Lớp học vui',
        fallbackProgramDetail1: 'Các hoạt động học tập nhẹ nhàng, giúp bé làm quen với môi trường lớp học.',
        fallbackProgramTitle2: 'Lớp vận động',
        fallbackProgramDetail2: 'Các trò chơi vận động giúp bé khỏe mạnh, nhanh nhẹn và tự tin hơn.',
        fallbackProgramTitle3: 'Lớp sáng tạo',
        fallbackProgramDetail3: 'Hoạt động vẽ, âm nhạc và thủ công giúp bé phát triển trí tưởng tượng.',
        fallbackTeacher1: 'Cô Nắng Hồng',
        fallbackTeacher2: 'Cô Hoa Mai',
        fallbackTeacher3: 'Cô Ánh Dương',
        fallbackTeacher4: 'Cô Bích Ngọc',
        kindergartenTeacher: 'Giáo viên mầm non',
        talentTeacher: 'Giáo viên năng khiếu',
        careTeacher: 'Giáo viên chăm sóc trẻ',
        classTeacher: 'Giáo viên lớp mẫu giáo',
        programAlt: 'Chương trình học',
        programFallbackDetail: 'Hoạt động học tập vui nhộn và phù hợp với trẻ mầm non.',
        viewDetail: 'Xem chi tiết',
        teacherAlt: 'Giáo viên',
        heroBadge: '🌞 Trường Mầm Non Nắng Hồng',
        heroTitle: 'Mỗi ngày đến trường là một ngày vui',
        heroDesc: 'Môi trường học tập ấm áp, an toàn, nhiều màu sắc và tràn đầy yêu thương cho các bé.',
        admission: 'Tuyển sinh',
        viewPrograms: 'Xem chương trình',
        programsBadge: 'Our Programs',
        programsTitle: 'Chương trình học vui nhộn',
        programsDesc: 'Các hoạt động học tập, vui chơi, vận động và sáng tạo dành cho trẻ mầm non.',
        aboutAlt: 'Giới thiệu Mầm Non Nắng Hồng',
        aboutTitle: 'Mỗi bé đều là một mặt trời nhỏ cần được yêu thương.',
        aboutDefaultQuote: 'Đội ngũ giáo viên tận tâm đồng hành cùng bé trong từng bước phát triển.',
        yearsExperience: 'Năm kinh nghiệm',
        studentsPerYear: 'Học sinh mỗi năm',
        achievements: 'Thành tích',
        teachersBadge: 'Teachers',
        teachersTitle: 'Đội ngũ giáo viên',
        teachersDesc: 'Các cô giáo yêu trẻ, tận tâm và luôn tạo cảm giác an toàn cho bé.',
        videoTitle: 'Video giới thiệu',
        videoDesc: 'Cùng nhìn lại môi trường học tập vui tươi tại Mầm Non Nắng Hồng.',
        openVideo: 'Mở video',
        noVideo: 'Chưa có video giới thiệu.',
        applyBadge: 'Tuyển sinh',
        applyTitle: 'Đăng ký tư vấn cho bé',
        applyDescPrefix: 'Thời gian tuyển sinh:',
        applyDescSuffix: 'Phụ huynh vui lòng để lại thông tin, nhà trường sẽ liên hệ tư vấn sớm nhất.',
        openNow: 'Đang mở',
        parentName: 'Tên phụ huynh *',
        parentNamePlaceholder: 'Nguyễn Văn A',
        phone: 'Số điện thoại *',
        phonePlaceholder: '090...',
        email: 'Email',
        emailPlaceholder: 'phuhuynh@email.com',
        childName: 'Tên bé *',
        childNamePlaceholder: 'Tên của bé',
        childAge: 'Tuổi của bé',
        childAgePlaceholder: '3',
        programRequired: 'Chương trình *',
        selectProgram: 'Chọn chương trình',
        message: 'Lời nhắn',
        messagePlaceholder: 'Phụ huynh cần tư vấn lớp học, học phí...',
        submitApplication: 'Gửi đăng ký',
        newsBadge: 'News',
        newsTitle: 'Tin tức Nắng Hồng',
        newsDesc: 'Những hoạt động và thông báo mới nhất của nhà trường.',
        noContent: 'Chưa có nội dung.',
        byAuthor: 'bởi',
        readMore: 'Đọc thêm',
        newsletterTitle: 'Đăng ký nhận tin',
        newsletterDesc: 'Nhận thông tin mới nhất về tuyển sinh và hoạt động của trường.',
        newsletterPlaceholder: 'Email của phụ huynh',
        subscribe: 'Đăng ký',
        footerDefault: 'Nơi bé được yêu thương, vui chơi và phát triển mỗi ngày.',
        quickLinks: 'Liên kết nhanh',
        footerAbout: 'Giới thiệu',
        footerPrograms: 'Chương trình',
        footerNews: 'Tin tức',
        footerContact: 'Liên hệ',
        contactTitle: 'Liên hệ',
        defaultAddress: 'Thành phố Hồ Chí Minh'
    },
    en: {
        brandName: 'Nang Hong Kindergarten',
        slogan: 'A happy learning place for children',
        navHome: 'Home',
        navAbout: 'About',
        navPrograms: 'Programs',
        navNews: 'News',
        navContact: 'Contact',
        applyNow: 'Apply Now',
        loadError: 'Unable to load homepage data',
        subscribeSuccessSummary: 'Subscribed successfully',
        subscribeSuccessDetail: 'Thank you for following Nang Hong Kindergarten',
        errorSummary: 'Error',
        subscribeError: 'Unable to subscribe to newsletter',
        applyMissingSummary: 'Missing information',
        applyMissingDetail: 'Please enter parent name, phone number, and child name',
        applyMissingProgramSummary: 'Missing program',
        applyMissingProgramDetail: 'Please choose a program for your child',
        applySuccessSummary: 'Registration sent',
        applySuccessDetail: 'The school will contact you as soon as possible',
        applyError: 'Unable to submit registration information',
        fallbackProgramTitle1: 'Happy Learning Class',
        fallbackProgramDetail1: 'Gentle learning activities that help children get familiar with the classroom environment.',
        fallbackProgramTitle2: 'Movement Class',
        fallbackProgramDetail2: 'Physical games that help children become healthier, more active, and more confident.',
        fallbackProgramTitle3: 'Creative Class',
        fallbackProgramDetail3: 'Drawing, music, and craft activities that develop children’s imagination.',
        fallbackTeacher1: 'Ms. Nang Hong',
        fallbackTeacher2: 'Ms. Hoa Mai',
        fallbackTeacher3: 'Ms. Anh Duong',
        fallbackTeacher4: 'Ms. Bich Ngoc',
        kindergartenTeacher: 'Kindergarten Teacher',
        talentTeacher: 'Talent Teacher',
        careTeacher: 'Childcare Teacher',
        classTeacher: 'Preschool Class Teacher',
        programAlt: 'Program',
        programFallbackDetail: 'Fun and age-appropriate learning activities for kindergarten children.',
        viewDetail: 'View Details',
        teacherAlt: 'Teacher',
        heroBadge: '🌞 Nang Hong Kindergarten',
        heroTitle: 'Every school day is a joyful day',
        heroDesc: 'A warm, safe, colorful, and caring learning environment for every child.',
        admission: 'Admission',
        viewPrograms: 'View Programs',
        programsBadge: 'Our Programs',
        programsTitle: 'Joyful Learning Programs',
        programsDesc: 'Learning, playing, movement, and creative activities designed for kindergarten children.',
        aboutAlt: 'About Nang Hong Kindergarten',
        aboutTitle: 'Every child is a little sun who deserves love and care.',
        aboutDefaultQuote: 'Dedicated teachers accompany children in every step of their growth journey.',
        yearsExperience: 'Years of Experience',
        studentsPerYear: 'Students Each Year',
        achievements: 'Achievements',
        teachersBadge: 'Teachers',
        teachersTitle: 'Our Teachers',
        teachersDesc: 'Caring teachers who love children and create a safe learning environment.',
        videoTitle: 'Introduction Video',
        videoDesc: 'Discover the joyful learning environment at Nang Hong Kindergarten.',
        openVideo: 'Open Video',
        noVideo: 'No introduction video available yet.',
        applyBadge: 'Admission',
        applyTitle: 'Register for Consultation',
        applyDescPrefix: 'Admission period:',
        applyDescSuffix: 'Parents can leave their information and the school will contact them soon.',
        openNow: 'Open now',
        parentName: 'Parent Name *',
        parentNamePlaceholder: 'Nguyen Van A',
        phone: 'Phone Number *',
        phonePlaceholder: '090...',
        email: 'Email',
        emailPlaceholder: 'parent@email.com',
        childName: 'Child Name *',
        childNamePlaceholder: 'Your child’s name',
        childAge: 'Child Age',
        childAgePlaceholder: '3',
        programRequired: 'Program *',
        selectProgram: 'Choose a program',
        message: 'Message',
        messagePlaceholder: 'Parents may ask about programs, tuition fees...',
        submitApplication: 'Submit Registration',
        newsBadge: 'News',
        newsTitle: 'Nang Hong News',
        newsDesc: 'Latest school activities and announcements.',
        noContent: 'No content yet.',
        byAuthor: 'by',
        readMore: 'Read More',
        newsletterTitle: 'Subscribe to Updates',
        newsletterDesc: 'Receive the latest admission and school activity updates.',
        newsletterPlaceholder: 'Parent email',
        subscribe: 'Subscribe',
        footerDefault: 'A place where children are loved, cared for, and encouraged to grow every day.',
        quickLinks: 'Quick Links',
        footerAbout: 'About',
        footerPrograms: 'Programs',
        footerNews: 'News',
        footerContact: 'Contact',
        contactTitle: 'Contact',
        defaultAddress: 'Ho Chi Minh City'
    }
} as const;

export type LandingLanguage = keyof typeof landingText;
