export const landingText = {
    vi: {
        brandName: 'Mầm Non Nắng Hồng',
        slogan: 'Nơi bé học vui mỗi ngày',
        navHome: 'Trang chủ',
        navAbout: 'Giới thiệu',
        navPrograms: 'Chương trình',
        navNews: 'Tin tức',
        navContact: 'Liên hệ',
        applyNow: 'Đăng ký ngay',
        loadError: 'Không tải được dữ liệu trang chủ',
        subscribeSuccessSummary: 'Đăng ký thành công',
        subscribeSuccessDetail: 'Cảm ơn bạn đã theo dõi Mầm Non Nắng Hồng',
        errorSummary: 'Lỗi',
        subscribeError: 'Không thể đăng ký newsletter',
        applyMissingSummary: 'Thiếu thông tin',
        applyMissingDetail: 'Vui lòng nhập tên phụ huynh, số điện thoại và tên bé',
        applyMissingProgramSummary: 'Thiếu chương trình',
        applyMissingProgramDetail: 'Vui lòng chọn chương trình cho bé',
        applySuccessSummary: 'Đăng ký thành công',
        applySuccessDetail: 'Nhà trường sẽ liên hệ phụ huynh trong thời gian sớm nhất',
        applyError: 'Không thể gửi thông tin đăng ký',
        fallbackProgramTitle1: 'Lớp học vui',
        fallbackProgramDetail1: 'Các hoạt động học tập nhẹ nhàng, giúp bé làm quen với môi trường lớp học.',
        fallbackProgramTitle2: 'Lớp vận động',
        fallbackProgramDetail2: 'Các trò chơi vận động giúp bé khỏe mạnh, nhanh nhẹn và tự tin hơn.',
        fallbackProgramTitle3: 'Lớp sáng tạo',
        fallbackProgramDetail3: 'Hoạt động vẽ, âm nhạc và thủ công giúp bé phát triển trí tưởng tượng.',
        fallbackTeacher1: 'Cô Nắng Hồng',
        fallbackTeacher2: 'Cô Hoa Mai',
        fallbackTeacher3: 'Cô Ánh Dương',
        fallbackTeacher4: 'Cô Bích Ngọc',
        kindergartenTeacher: 'Giáo viên mầm non',
        talentTeacher: 'Giáo viên năng khiếu',
        careTeacher: 'Giáo viên chăm sóc trẻ',
        classTeacher: 'Giáo viên lớp mẫu giáo',
        programAlt: 'Chương trình học',
        programFallbackDetail: 'Hoạt động học tập vui nhộn và phù hợp với trẻ mầm non.',
        viewDetail: 'Xem chi tiết',
        teacherAlt: 'Giáo viên',
        heroBadge: '🌞 Trường Mầm Non Nắng Hồng',
        heroTitle: 'Mỗi ngày đến trường là một ngày vui',
        heroDesc: 'Môi trường học tập ấm áp, an toàn, nhiều màu sắc và tràn đầy yêu thương cho các bé.',
        admission: 'Tuyển sinh',
        viewPrograms: 'Xem chương trình',
        programsBadge: 'Our Programs',
        programsTitle: 'Chương trình học vui nhộn',
        programsDesc: 'Các hoạt động học tập, vui chơi, vận động và sáng tạo dành cho trẻ mầm non.',
        aboutAlt: 'Giới thiệu Mầm Non Nắng Hồng',
        aboutTitle: 'Mỗi bé đều là một mặt trời nhỏ cần được yêu thương.',
        aboutDefaultQuote: 'Đội ngũ giáo viên tận tâm đồng hành cùng bé trong từng bước phát triển.',
        yearsExperience: 'Năm kinh nghiệm',
        studentsPerYear: 'Học sinh mỗi năm',
        achievements: 'Thành tích',
        teachersBadge: 'Teachers',
        teachersTitle: 'Đội ngũ giáo viên',
        teachersDesc: 'Các cô giáo yêu trẻ, tận tâm và luôn tạo cảm giác an toàn cho bé.',
        videoTitle: 'Video giới thiệu',
        videoDesc: 'Cùng nhìn lại môi trường học tập vui tươi tại Mầm Non Nắng Hồng.',
        openVideo: 'Mở video',
        noVideo: 'Chưa có video giới thiệu.',
        applyBadge: 'Tuyển sinh',
        applyTitle: 'Đăng ký tư vấn cho bé',
        applyDescPrefix: 'Thời gian tuyển sinh:',
        applyDescSuffix: 'Phụ huynh vui lòng để lại thông tin, nhà trường sẽ liên hệ tư vấn sớm nhất.',
        openNow: 'Đang mở',
        parentName: 'Tên phụ huynh *',
        parentNamePlaceholder: 'Nguyễn Văn A',
        phone: 'Số điện thoại *',
        phonePlaceholder: '090...',
        email: 'Email',
        emailPlaceholder: 'phuhuynh@email.com',
        childName: 'Tên bé *',
        childNamePlaceholder: 'Tên của bé',
        childAge: 'Tuổi của bé',
        childAgePlaceholder: '3',
        programRequired: 'Chương trình *',
        selectProgram: 'Chọn chương trình',
        message: 'Lời nhắn',
        messagePlaceholder: 'Phụ huynh cần tư vấn lớp học, học phí...',
        submitApplication: 'Gửi đăng ký',
        newsBadge: 'News',
        newsTitle: 'Tin Tức Nắng Hồng',
        newsDesc: 'Những hoạt động và thông báo mới nhất của nhà trường.',
        noContent: 'Chưa có nội dung.',
        byAuthor: 'bởi',
        readMore: 'Đọc thêm',
        newsletterTitle: 'Đăng ký nhận tin',
        newsletterDesc: 'Nhận thông tin mới nhất về tuyển sinh và hoạt động của trường.',
        newsletterPlaceholder: 'Email của phụ huynh',
        subscribe: 'Đăng ký',
        footerDefault: 'Nơi bé được yêu thương, vui chơi và phát triển mỗi ngày.',
        quickLinks: 'Liên kết nhanh',
        footerAbout: 'Giới thiệu',
        footerPrograms: 'Chương trình',
        footerNews: 'Tin tức',
        footerContact: 'Liên hệ',
        contactTitle: 'Liên hệ',
        defaultAddress: 'Thành Phố Hồ Chí Minh',
        // Highlights Section
        highlightsBadge: 'Điểm Nổi Bật',
        highlightsTitle: 'Vì sao phụ huynh tin chọn Nắng Hồng?',
        highlightsDesc: 'Những giá trị nền tảng giúp bé phát triển toàn diện và hạnh phúc mỗi ngày.',
        highlight1Title: 'Phương Pháp Tiên Tiến',
        highlight1Desc: 'Ứng dụng giáo dục sớm lấy trẻ làm trung tâm, tôn trọng sự phát triển tự nhiên của bé.',
        highlight2Title: 'Camera Trực Tuyến 24/7',
        highlight2Desc: 'Hệ thống camera góc rộng tại các lớp giúp ba mẹ luôn an tâm dõi theo từng khoảnh khắc của con.',
        highlight3Title: 'Không Gian Mở & Xanh',
        highlight3Desc: 'Sân chơi tự nhiên tràn ngập ánh sáng, cây xanh cùng khu vận động thể chất an toàn.',
        highlight4Title: 'Dinh Dưỡng Hữu Cơ',
        highlight4Desc: 'Thực đơn cân đối theo tiêu chuẩn viện dinh dưỡng, 100% nguyên liệu tươi sạch rõ nguồn gốc.',
        highlight5Title: 'Sĩ Số Lớp Học Nhỏ',
        highlight5Desc: 'Tỷ lệ cô/trẻ chuẩn giúp các cô chăm sóc tỉ mỉ, sát sao theo tính cách từng bé.',
        highlight6Title: 'Y Tế & Vệ Sinh Nghiêm Ngặt',
        highlight6Desc: 'Kiểm tra thân nhiệt mỗi sáng, đồ dùng đồ chơi được tiệt trùng hàng ngày theo quy chuẩn y tế.',
        // Facilities Section
      facilitiesBadge: 'Cơ Sở Vật Chất',
        facilitiesTitle: 'Không gian học tập & vui chơi ấm cúng',
        facilitiesDesc: 'Môi trường an toàn, gần gũi, trang bị đầy đủ học cụ và đồ chơi giúp bé vui vẻ mỗi ngày.',
        facilityMam: 'Lớp Mầm (3 tuổi)',
        facilityMamDesc: 'Không gian rộng rãi, thoáng mát, góc chơi phong phú giúp bé làm quen nề nếp sinh hoạt.',
        facilityChoi: 'Lớp Chồi (4 tuổi)',
        facilityChoiDesc: 'Bố trí khoa học với bàn ghế chuẩn lứa tuổi, kích thích tính tương tác và phát triển kỹ năng xã hội.',
        facilityLa: 'Lớp Lá (5 tuổi)',
        facilityLaDesc: 'Trang bị góc làm quen chữ cái, con số và rèn luyện tư duy chuẩn bị hành trang vào Lớp 1.',
        facilityPlayCorner: 'Phòng Đồ Chơi Vận Động',
        facilityPlayCornerDesc: 'Khu vực trò chơi giải trí, nhà banh, lắp ghép thông minh cho bé thỏa sức nô đùa an toàn.',
        facilityFreePlay: 'Sân Chơi Tự Do',
        facilityFreePlayDesc: 'Khoảng sân thoáng đãng để bé tập thể dục sáng, tham gia trò chơi dân gian và tắm nắng.',
        facilityOffice: 'Văn Phòng & Đón Tiếp',
        facilityOfficeDesc: 'Nơi tiếp nhận hồ sơ, trao đổi thông tin hàng ngày và phối hợp chăm sóc cùng phụ huynh.',
        // Nutrition & Health Section
        nutritionBadge: 'Dinh Dưỡng & Sức Khỏe',
        nutritionTitle: 'Chế độ dinh dưỡng chuẩn & Y tế học đường',
        nutritionDesc: 'Đảm bảo mỗi bữa ăn ngon miệng, cân bằng vi chất cùng quy trình theo dõi sức khỏe toàn diện cho bé.',
        mealScheduleTitle: 'Thời gian biểu 4 cữ ăn khoa học',
        breakfastTitle: 'Bữa Sáng Năng Lượng (7:30 - 8:15)',
        breakfastDesc: 'Món ăn nóng dễ tiêu hóa (cháo tôm bí đỏ, phở gà ta, nui xào bò...) cung cấp năng lượng khởi đầu ngày mới.',
        morningSnackTitle: 'Bữa Phụ Sáng (9:30 - 9:45)',
        morningSnackDesc: 'Sữa hạt nguyên chất hữu cơ, nước ép trái cây tươi hoặc sữa chua thanh trùng giúp bù nước và vitamin.',
        lunchTitle: 'Bữa Trưa Đủ Chất (11:00 - 11:45)',
        lunchDesc: 'Món mặn + canh rau + cơm dẻo + tráng miệng, cân đối 4 nhóm dưỡng chất: đạm, béo, đường bột, khoáng chất.',
        afternoonSnackTitle: 'Bữa Xế Chiều (14:30 - 15:15)',
        afternoonSnackDesc: 'Bánh flan tươi, súp dinh dưỡng, ngũ cốc hoặc chè hạt sen bồi dưỡng sau giấc ngủ trưa.',
        commit1Title: 'Thực phẩm sạch 100%',
        commit1Desc: 'Nguồn thịt rau củ tươi sạch có chứng nhận VietGAP, nguồn gốc xuất xứ rõ ràng mỗi ngày.',
        commit2Title: 'Lưu mẫu chuẩn Bộ Y Tế',
        commit2Desc: 'Toàn bộ mẫu thức ăn được niêm phong lưu trữ 24h nghiêm ngặt dưới sự giám sát của cán bộ y tế.',
        commit3Title: 'Khám sức khỏe định kỳ',
        commit3Desc: 'Đo chiều cao, cân nặng hàng tháng, phối hợp trạm y tế khám mắt, tai mũi họng và răng miệng 2 lần/năm.',
        // Tuition & Fees Section
        // Tuition & Fees Section (Banner chung)
        tuitionBadge: 'Học Phí Minh Bạch',
        tuitionTitle: 'Chi phí hợp lý & Đồng hành cùng gia đình',
        tuitionDesc: 'Mức học phí trọn gói phù hợp, minh bạch và ổn định cho các bé từ 3 đến 5 tuổi.',
        tuitionRangePrice: '2.800.000đ – 3.000.000đ',
        tuitionMonth: '/ tháng',
        tuitionScope: 'Áp dụng cho các khối lớp Mầm (3 tuổi), Chồi (4 tuổi) và Lá (5 tuổi)',
        tuitionFeatureMeal: 'Tiền ăn bán trú: 55.000đ / ngày (đủ các cữ ăn dinh dưỡng)',
        tuitionFeatureCamera: 'Theo dõi hoạt động & camera kết nối phụ huynh',
        tuitionFeatureInsurance: 'Chăm sóc sức khỏe & theo dõi thể trạng định kỳ',
        tuitionFeatureActivities: 'Chương trình học trải nghiệm & sự kiện lễ hội vui vẻ',
        tuitionFeeInclude: 'Lưu ý về các khoản phụ trợ:',
        tuitionMealFeeTitle: 'Tiền ăn bán trú:',
        tuitionMealFeeValue: '55.000đ / ngày',
        tuitionMaterialFeeTitle: 'Học liệu & đồ dùng năm học:',
        tuitionMaterialFeeValue: '1.200.000đ / năm',
        tuitionLateFeeTitle: 'Hỗ trợ trông muộn sau giờ đón:',
        tuitionLateFeeValue: 'Linh hoạt theo nhu cầu phụ huynh',
        tuitionDiscountBannerTitle: '🎁 Ưu đãi tuyển sinh',
        tuitionDiscountBannerDesc: 'Tặng bộ đồ dùng học tập và ưu đãi học phí cho phụ huynh đăng ký sớm trong tháng.',
        tuitionRegisterNow: 'Đăng ký nhận tư vấn',
        // Map & Location
        mapBadge: 'Vị Trí & Liên Hệ',
        mapTitle: 'Ghé thăm Mầm Non Nắng Hồng',
        mapDesc: 'Nhà trường luôn chào đón quý phụ huynh và các bé đến tham quan trực tiếp khuôn viên trường.',
        mapAddressLabel: 'Địa chỉ trường:',
        mapWorkingHoursLabel: 'Giờ đón tiếp phụ huynh:',
        mapWorkingHoursValue: 'Thứ 2 - Thứ 6: 7:00 - 17:30 | Thứ 7: 7:30 - 11:30',
        mapGetDirections: 'Xem chỉ đường trên Google Maps',
    },
    en: {
        brandName: 'Nang Hong Kindergarten',
        slogan: 'A happy learning place for children',
        navHome: 'Home',
        navAbout: 'About',
        navPrograms: 'Programs',
        navNews: 'News',
        navContact: 'Contact',
        applyNow: 'Apply Now',
        loadError: 'Unable to load homepage data',
        subscribeSuccessSummary: 'Subscribed successfully',
        subscribeSuccessDetail: 'Thank you for following Nang Hong Kindergarten',
        errorSummary: 'Error',
        subscribeError: 'Unable to subscribe to newsletter',
        applyMissingSummary: 'Missing information',
        applyMissingDetail: 'Please enter parent name, phone number, and child name',
        applyMissingProgramSummary: 'Missing program',
        applyMissingProgramDetail: 'Please choose a program for your child',
        applySuccessSummary: 'Registration sent',
        applySuccessDetail: 'The school will contact you as soon as possible',
        applyError: 'Unable to submit registration information',
        fallbackProgramTitle1: 'Happy Learning Class',
        fallbackProgramDetail1: 'Gentle learning activities that help children get familiar with the classroom environment.',
        fallbackProgramTitle2: 'Movement Class',
        fallbackProgramDetail2: 'Physical games that help children become healthier, more active, and more confident.',
        fallbackProgramTitle3: 'Creative Class',
        fallbackProgramDetail3: 'Drawing, music, and craft activities that develop children’s imagination.',
        fallbackTeacher1: 'Ms. Nang Hong',
        fallbackTeacher2: 'Ms. Hoa Mai',
        fallbackTeacher3: 'Ms. Anh Duong',
        fallbackTeacher4: 'Ms. Bich Ngoc',
        kindergartenTeacher: 'Kindergarten Teacher',
        talentTeacher: 'Talent Teacher',
        careTeacher: 'Childcare Teacher',
        classTeacher: 'Preschool Class Teacher',
        programAlt: 'Program',
        programFallbackDetail: 'Fun and age-appropriate learning activities for kindergarten children.',
        viewDetail: 'View Details',
        teacherAlt: 'Teacher',
        heroBadge: '🌞 Nang Hong Kindergarten',
        heroTitle: 'Every school day is a joyful day',
        heroDesc: 'A warm, safe, colorful, and caring learning environment for every child.',
        admission: 'Admission',
        viewPrograms: 'View Programs',
        programsBadge: 'Our Programs',
        programsTitle: 'Joyful Learning Programs',
        programsDesc: 'Learning, playing, movement, and creative activities designed for kindergarten children.',
        aboutAlt: 'About Nang Hong Kindergarten',
        aboutTitle: 'Every child is a little sun who deserves love and care.',
        aboutDefaultQuote: 'Dedicated teachers accompany children in every step of their growth journey.',
        yearsExperience: 'Years of Experience',
        studentsPerYear: 'Students Each Year',
        achievements: 'Achievements',
        teachersBadge: 'Teachers',
        teachersTitle: 'Our Teachers',
        teachersDesc: 'Caring teachers who love children and create a safe learning environment.',
        videoTitle: 'Introduction Video',
        videoDesc: 'Discover the joyful learning environment at Nang Hong Kindergarten.',
        openVideo: 'Open Video',
        noVideo: 'No introduction video available yet.',
        applyBadge: 'Admission',
        applyTitle: 'Register for Consultation',
        applyDescPrefix: 'Admission period:',
        applyDescSuffix: 'Parents can leave their information and the school will contact them soon.',
        openNow: 'Open now',
        parentName: 'Parent Name *',
        parentNamePlaceholder: 'Nguyen Van A',
        phone: 'Phone Number *',
        phonePlaceholder: '090...',
        email: 'Email',
        emailPlaceholder: 'parent@email.com',
        childName: 'Child Name *',
        childNamePlaceholder: 'Your child’s name',
        childAge: 'Child Age',
        childAgePlaceholder: '3',
        programRequired: 'Program *',
        selectProgram: 'Choose a program',
        message: 'Message',
        messagePlaceholder: 'Parents may ask about programs, tuition fees...',
        submitApplication: 'Submit Registration',
        newsBadge: 'News',
        newsTitle: 'Nang Hong News',
        newsDesc: 'Latest school activities and announcements.',
        noContent: 'No content yet.',
        byAuthor: 'by',
        readMore: 'Read More',
        newsletterTitle: 'Subscribe to Updates',
        newsletterDesc: 'Receive the latest admission and school activity updates.',
        newsletterPlaceholder: 'Parent email',
        subscribe: 'Subscribe',
        footerDefault: 'A place where children are loved, cared for, and encouraged to grow every day.',
        quickLinks: 'Quick Links',
        footerAbout: 'About',
        footerPrograms: 'Programs',
        footerNews: 'News',
        footerContact: 'Contact',
        contactTitle: 'Contact',
        defaultAddress: 'Ho Chi Minh City',
        // Highlights Section
        highlightsBadge: 'Key Highlights',
        highlightsTitle: 'Why Parents Choose Nang Hong?',
        highlightsDesc: 'Core values that foster holistic growth and daily joy for every child.',
        highlight1Title: 'Modern Methodology',
        highlight1Desc: 'Child-centered early education respecting each child’s natural developmental pace.',
        highlight2Title: '24/7 Online Camera',
        highlight2Desc: 'Wide-angle camera system across classrooms giving parents peace of mind anytime, anywhere.',
        highlight3Title: 'Green & Open Space',
        highlight3Desc: 'Sunlit outdoor playground with green trees and child-safe physical activity zones.',
        highlight4Title: 'Organic Nutrition',
        highlight4Desc: 'Balanced meals based on nutrition institute standards with 100% fresh, traceable ingredients.',
        highlight5Title: 'Low Student-Teacher Ratio',
        highlight5Desc: 'Small class sizes allow teachers to closely care for and understand each child individually.',
        highlight6Title: 'Strict Hygiene & Healthcare',
        highlight6Desc: 'Daily morning temperature check-ins and toys sanitized daily following medical guidelines.',
        // Facilities Section
        facilitiesBadge: 'Campus & Classrooms',
        facilitiesTitle: 'Cozy Learning & Play Spaces',
        facilitiesDesc: 'Safe, warm environment well-equipped with toys and learning tools for children.',
        facilityMam: 'Mam Class (3 Years Old)',
        facilityMamDesc: 'Spacious and airy room with diverse play corners helping children adapt to routines.',
        facilityChoi: 'Choi Class (4 Years Old)',
        facilityChoiDesc: 'Thoughtful setup fostering social interactions and active collaboration with peers.',
        facilityLa: 'La Class (5 Years Old)',
        facilityLaDesc: 'Pre-primary preparation with letters, basic counting, and school readiness skills.',
        facilityPlayCorner: 'Indoor Toy & Activity Room',
        facilityPlayCornerDesc: 'Fun entertainment zone with smart building blocks and toys for active physical play.',
        facilityFreePlay: 'Free Play Yard',
        facilityFreePlayDesc: 'Open outdoor yard for morning exercise, traditional games, and healthy fresh air.',
        facilityOffice: 'Combined Office & Reception',
        facilityOfficeDesc: 'Dedicated space for parent consultations, admissions, and daily coordination.',
        // Nutrition & Health Section
        nutritionBadge: 'Nutrition & Healthcare',
        nutritionTitle: 'Balanced Meals & Comprehensive Healthcare',
        nutritionDesc: 'Delivering delicious, balanced nutrition paired with proactive health tracking for every child.',
        mealScheduleTitle: '4-Meal Daily Nutrition Schedule',
        breakfastTitle: 'Energizing Breakfast (7:30 - 8:15)',
        breakfastDesc: 'Warm, easily digestible meals (pumpkin shrimp porridge, chicken pho, pasta) powering an active morning.',
        morningSnackTitle: 'Morning Boost (9:30 - 9:45)',
        morningSnackDesc: 'Organic nut milk, freshly squeezed fruit juices, or pasteurized yogurt replenishing vitamins.',
        lunchTitle: 'Wholesome Lunch (11:00 - 11:45)',
        lunchDesc: 'Balanced meal with 4 vital nutrient groups: protein, carbs, healthy fats, minerals, and fresh dessert.',
        afternoonSnackTitle: 'Afternoon Refresh (14:30 - 15:15)',
        afternoonSnackDesc: 'Light post-nap refreshment including homemade flan, nutritious soup, cereals, or lotus seed sweet soup.',
        commit1Title: '100% Certified Clean Food',
        commit1Desc: 'VietGAP certified meats and organic fresh vegetables daily with complete provenance transparency.',
        commit2Title: '24H Sample Food Preservation',
        commit2Desc: 'All meals are sampled and sealed for 24 hours under the supervision of medical staff.',
        commit3Title: 'Periodic Health Check-ups',
        commit3Desc: 'Monthly height & weight monitoring, plus bi-annual dental, vision, and ENT screening.',
        // Tuition & Fees Section
        // Tuition & Fees Section
        tuitionBadge: 'Transparent Tuition',
        tuitionTitle: 'Affordable & Family-Friendly Fees',
        tuitionDesc: 'A stable, transparent, and all-inclusive tuition structure for children aged 3 to 5.',
        tuitionRangePrice: '2,800,000 – 3,000,000 VND',
        tuitionMonth: '/ month',
        tuitionScope: 'Applicable across Mam (3yo), Choi (4yo), and La (5yo) classes',
        tuitionFeatureMeal: 'Boarding meals: 55,000 VND / day (wholesome meals included)',
        tuitionFeatureCamera: 'Daily activities & parent connection monitoring',
        tuitionFeatureInsurance: 'Healthcare & regular development monitoring',
        tuitionFeatureActivities: 'Hands-on learning activities & seasonal events',
        tuitionFeeInclude: 'Supplementary fee notes:',
        tuitionMealFeeTitle: 'Boarding meals:',
        tuitionMealFeeValue: '55,000 VND / day',
        tuitionMaterialFeeTitle: 'Learning materials & equipment:',
        tuitionMaterialFeeValue: '1,200,000 VND / year',
        tuitionLateFeeTitle: 'Late pick-up support:',
        tuitionLateFeeValue: 'Flexible upon parent request',
        tuitionDiscountBannerTitle: '🎁 Enrollment Promotion',
        tuitionDiscountBannerDesc: 'Free stationery kit and special tuition offers for early enrollments this month.',
        tuitionRegisterNow: 'Register for Consultation',
        // Map & Location
        mapBadge: 'Location & Campus',
        mapTitle: 'Visit Nang Hong Kindergarten',
        mapDesc: 'We warmly welcome parents and children to visit and tour our school campus.',
        mapAddressLabel: 'Campus Address:',
        mapWorkingHoursLabel: 'Visiting Hours:',
        mapWorkingHoursValue: 'Mon - Fri: 7:00 AM - 5:30 PM | Sat: 7:30 AM - 11:30 AM',
        mapGetDirections: 'Open in Google Maps',
    }
} as const;

export type LandingLanguage = keyof typeof landingText;
