export const landingText = {
    vi: {
        brandName: 'Mầm Non Nắng Hồng',
        slogan: 'Nơi bé học vui mỗi ngày - Ươm mầm hạnh phúc tuổi thơ',
        // Trong khối vi:
        navHome: 'Trang chủ',
        navAbout: 'Giới thiệu',
        navPrograms: 'Chương trình',
        navFacilities: 'Cơ sở vật chất',
        navTuition: 'Học phí',
        navNews: 'Tin tức',
        navContact: 'Liên hệ',
        applyNow: 'Đăng ký tư vấn ngay',
        loadError: 'Không tải được dữ liệu trang chủ, quý phụ huynh vui lòng tải lại trang.',
        subscribeSuccessSummary: 'Đăng ký thành công',
        subscribeSuccessDetail: 'Cảm ơn ba mẹ đã theo dõi và đồng hành cùng Mầm Non Nắng Hồng.',
        errorSummary: 'Đã có lỗi xảy ra',
        subscribeError: 'Không thể đăng ký nhận tin lúc này, vui lòng thử lại sau.',
        applyMissingSummary: 'Thiếu thông tin đăng ký',
        applyMissingDetail: 'Vui lòng nhập đầy đủ họ tên phụ huynh, số điện thoại và tên bé để trường hỗ trợ tốt nhất.',
        applyMissingProgramSummary: 'Chưa chọn khối lớp',
        applyMissingProgramDetail: 'Vui lòng lựa chọn khối lớp phù hợp với độ tuổi của bé.',
        applySuccessSummary: 'Gửi thông tin thành công',
        applySuccessDetail: 'Ban giám hiệu Mầm Non Nắng Hồng sẽ liên hệ phụ huynh trong thời gian sớm nhất.',
        applyError: 'Không thể gửi thông tin đăng ký lúc này, vui lòng thử lại.',
        fallbackProgramTitle1: 'Lớp Mầm (3 Tuổi) - Vui Vẻ Làm Quen',
        fallbackProgramDetail1: 'Những bước chân đầu đời bước vào nếp sinh hoạt tập thể, học cách chia sẻ đồ chơi và tự lập cơ bản trong vòng tay yêu thương của các cô.',
        fallbackProgramTitle2: 'Lớp Chồi (4 Tuổi) - Khám Phá & Tự Lập',
        fallbackProgramDetail2: 'Rèn luyện kỹ năng vận động tinh, giao tiếp mạch lạc, khơi gợi trí tò mò tự nhiên qua các hoạt động trải nghiệm trực quan sinh động.',
        fallbackProgramTitle3: 'Lớp Lá (5 Tuổi) - Vững Vàng Vào Lớp 1',
        fallbackProgramDetail3: 'Trang bị nền tảng tiền tiểu học vững chắc về tư duy ngôn ngữ, các phép đếm cơ bản và rèn luyện tâm lý tự tin, sẵn sàng vào trường tiểu học.',
        fallbackTeacher1: 'Cô Nắng Hồng',
        fallbackTeacher2: 'Cô Hoa Mai',
        fallbackTeacher3: 'Cô Ánh Dương',
        fallbackTeacher4: 'Cô Bích Ngọc',
        kindergartenTeacher: 'Giáo viên chủ nhiệm mầm non',
        talentTeacher: 'Giáo viên năng khiếu & âm nhạc',
        careTeacher: 'Giáo viên phụ trách chăm sóc & dinh dưỡng',
        classTeacher: 'Giáo viên mầm non phụ trách khối lớp',
        programAlt: 'Chương trình giáo dục mầm non',
        programFallbackDetail: 'Chương trình chuẩn của Bộ Giáo dục & Đào tạo kết hợp các hoạt động trải nghiệm thực tế, vận động và phát triển nhận thức toàn diện.',
        viewDetail: 'Xem chi tiết lớp học',
        teacherAlt: 'Đội ngũ giáo viên Mầm Non Nắng Hồng',
        heroBadge: '🌞 Trường Mầm Non Nắng Hồng - Ngôi Nhà Thứ Hai Của Bé',
        heroTitle: 'Mỗi ngày đến trường là một ngày vui trọn vẹn',
        heroDesc: 'Thấu hiểu rằng những năm tháng đầu đời là giai đoạn vàng định hình nhân cách và cảm xúc của trẻ, Nắng Hồng mang đến một không gian ấm áp, an toàn và ngập tràn tình thương yêu. Nơi đây, mỗi đứa trẻ đều được lắng nghe, tự do thể hiện suy nghĩ và lớn khôn trong hạnh phúc.',
        admission: 'Đăng ký nhập học',
        viewPrograms: 'Khám phá các lớp',
        programsBadge: 'Chương Trình Đào Tạo',
        programsTitle: 'Chương trình học tập & Trải nghiệm thực tế',
        programsDesc: 'Nhà trường chú trọng phương pháp giáo dục trực quan, gắn liền việc học với vui chơi và vận động thực tế, giúp các con tiếp thu kiến thức một cách tự nhiên và nhẹ nhàng nhất.',
        aboutAlt: 'Giới thiệu về Mầm Non Nắng Hồng',
        aboutTitle: 'Mỗi đứa trẻ là một mầm xanh duy nhất cần được nâng niu.',
        aboutDefaultQuote: 'Tại Nắng Hồng, chúng tôi không áp đặt khuôn mẫu lên trẻ nhỏ. Sứ mệnh của các cô giáo là kiên nhẫn làm bạn cùng con, khơi dậy niềm vui thích khám phá thế giới xung quanh và vun đắp cho con một tâm hồn nhân ái, tự tin và khỏe mạnh.',
        yearsExperience: 'Năm kinh nghiệm',
        studentsPerYear: 'Bé vui học mỗi năm',
        achievements: 'Bằng khen & Thành tích',
        teachersBadge: 'Đội Ngũ Giáo Viên',
        teachersTitle: 'Những người mẹ hiền thứ hai của các con',
        teachersDesc: '100% giáo viên có bằng cấp chuyên môn sư phạm mầm non, tận tụy, kiên nhẫn và luôn coi sự an toàn, nụ cười của các bé là niềm hạnh phúc lớn nhất mỗi ngày.',
        videoTitle: 'Một ngày tại Nắng Hồng',
        videoDesc: 'Mời ba mẹ cùng dõi theo những khoảnh khắc vui tươi, bữa ăn ngon miệng và tiếng cười rộn rã của các con trong một ngày sinh hoạt thực tế tại trường.',
        openVideo: 'Xem video đầy đủ',
        noVideo: 'Video giới thiệu trường đang được cập nhật.',
        applyBadge: 'Tuyển Sinh Niên Khóa Mới',
        applyTitle: 'Đăng ký tư vấn & Tham quan trường',
        applyDescPrefix: 'Thời gian tuyển sinh:',
        applyDescSuffix: 'Nhà trường luôn sẵn sàng chào đón quý phụ huynh cùng bé đến trải nghiệm lớp học thực tế và nhận tư vấn chi tiết từ Ban giám hiệu.',
        openNow: 'Đang tiếp nhận hồ sơ',
        parentName: 'Họ và tên phụ huynh *',
        parentNamePlaceholder: 'Ví dụ: Nguyễn Văn A',
        phone: 'Số điện thoại liên hệ *',
        phonePlaceholder: 'Ví dụ: 0901 234 567',
        email: 'Địa chỉ Email (nếu có)',
        emailPlaceholder: 'phuhuynh@gmail.com',
        childName: 'Họ và tên của bé *',
        childNamePlaceholder: 'Ví dụ: Bé An Nhiên',
        childAge: 'Độ tuổi của bé',
        childAgePlaceholder: 'Ví dụ: 3 tuổi (Lớp Mầm)',
        programRequired: 'Chọn khối lớp học cho bé *',
        selectProgram: '-- Chọn khối lớp phù hợp --',
        message: 'Lời nhắn hoặc câu hỏi dành cho nhà trường',
        messagePlaceholder: 'Ba mẹ cần tư vấn thêm về thời gian đưa đón, chế độ ăn của bé hoặc đặt lịch tham quan trường...',
        submitApplication: 'Gửi thông tin đăng ký',
        newsBadge: 'Tin Tức & Sự Kiện',
        newsTitle: 'Nhịp sống vui tươi tại Nắng Hồng',
        newsDesc: 'Cập nhật những hình ảnh lễ hội, hoạt động ngoại khóa, thực đơn tuần và thông báo quan trọng từ nhà trường.',
        noContent: 'Nội dung thông báo đang được cập nhật.',
        byAuthor: 'Đăng bởi',
        readMore: 'Đọc chi tiết bài viết',
        newsletterTitle: 'Đăng ký nhận bản tin Nắng Hồng',
        newsletterDesc: 'Nhận ngay những chia sẻ hữu ích về kinh nghiệm nuôi dạy con, thực đơn dinh dưỡng và thông tin tuyển sinh mới nhất từ nhà trường qua email.',
        newsletterPlaceholder: 'Nhập email của ba mẹ...',
        subscribe: 'Đăng ký nhận tin',
        footerDefault: 'Mầm Non Nắng Hồng tự hào là địa chỉ giáo dục uy tín, nơi gửi gắm niềm tin trọn vẹn của các bậc phụ huynh trong những năm tháng đầu đời quý giá của con trẻ.',
        quickLinks: 'Khám phá nhanh',
        footerAbout: 'Về nhà trường',
        footerPrograms: 'Chương trình học',
        footerNews: 'Bảng tin hoạt động',
        footerContact: 'Thông tin liên hệ',
        contactTitle: 'Văn phòng tuyển sinh',
        defaultAddress: 'Thành phố Hồ Chí Minh, Việt Nam',

        // Highlights Section (Chuẩn KiddiHub)
        highlightsBadge: 'Giá Trị Cốt Lõi',
        highlightsTitle: 'Vì sao phụ huynh luôn an tâm gửi gắm con tại Nắng Hồng?',
        highlightsDesc: 'Chúng tôi xây dựng môi trường giáo dục dựa trên nền tảng tình yêu thương, sự tôn trọng và đồng hành chặt chẽ cùng gia đình trong từng chặng đường khôn lớn của bé.',
        highlight1Title: 'Phương Pháp Lấy Trẻ Làm Trung Tâm',
        highlight1Desc: 'Không áp lực học thuật gò bó, chương trình giáo dục giúp các con học qua trải nghiệm thực tế, khuyến khích sự tự lập, tính tò mò và bộc lộ năng khiếu tự nhiên.',
        highlight2Title: 'Camera Trực Tuyến Kết Nối 24/7',
        highlight2Desc: 'Hệ thống camera sắc nét góc nhìn bao quát toàn bộ lớp học và khu vui chơi, giúp ba mẹ luôn có cảm giác đồng hành bên con mọi lúc mọi nơi ngay trên điện thoại.',
        highlight3Title: 'Không Gian Học Tập Ấm Cúng & Gần Gũi',
        highlight3Desc: 'Lớp học được thiết kế đón nhận tối đa ánh sáng mặt trời tự nhiên, sàn lót sạch sẽ, bàn ghế chuẩn nhân trắc học mầm non, tạo cảm giác thân thuộc như tại gia đình.',
        highlight4Title: 'Dinh Dưỡng Cân Bằng & Thực Phẩm Tươi Sạch',
        highlight4Desc: 'Thực đơn 4 cữ ăn được tính toán khoa học theo viện dinh dưỡng, 100% nguyên liệu tươi sống sạch mỗi ngày với quy trình chế biến một chiều đạt chuẩn vệ sinh.',
        highlight5Title: 'Sĩ Số Lớp Tối Ưu - Chăm Sóc Sát Sao',
        highlight5Desc: 'Tỷ lệ trẻ trên cô luôn được duy trì ở mức chuẩn để giáo viên có thể quan sát, thấu hiểu tâm lý, kiên nhẫn vỗ về và hỗ trợ nếp ăn ngủ của từng con.',
        highlight6Title: 'Quy Trình Chăm Sóc Sức Khỏe & An Toàn Cao',
        highlight6Desc: 'Đón trẻ và kiểm tra thân nhiệt mỗi sáng, đồ dùng ăn uống và đồ chơi được khử khuẩn định kỳ, đảm bảo không gian luôn sạch sẽ và hạn chế tối đa các bệnh truyền nhiễm.',

        // Facilities Section (Đúng thực tế: 3 lớp Mầm - Chồi - Lá, Phòng đồ chơi, Sân tự do, Văn phòng)
        facilitiesBadge: 'Cơ Sở Vật Chất',
        facilitiesTitle: 'Không gian học tập & sinh hoạt an toàn, thân thiện',
        facilitiesDesc: 'Mỗi góc không gian tại Nắng Hồng đều được bài trí tỉ mỉ, tối ưu hóa độ an toàn nhằm mang lại cho trẻ sự thoải mái, tự do vận động và phát huy khả năng sáng tạo.',
        facilityMam: 'Lớp Mầm (Dành cho trẻ 3 tuổi)',
        facilityMamDesc: 'Không gian ấm áp, chan hòa ánh sáng với góc đồ chơi mềm, bàn ghế chuẩn lứa tuổi giúp các bé bớt cảm giác bỡ ngỡ, nhanh chóng thích nghi với nề nếp sinh hoạt lớp.',
        facilityChoi: 'Lớp Chồi (Dành cho trẻ 4 tuổi)',
        facilityChoiDesc: 'Bố trí các góc hoạt động phong phú: góc tạo hình, góc bác sĩ, góc gia đình... kích thích ngôn ngữ giao tiếp, khả năng làm việc nhóm và tinh thần đoàn kết của bé.',
        facilityLa: 'Lớp Lá (Dành cho trẻ 5 tuổi)',
        facilityLaDesc: 'Trang bị góc nhận biết bảng chữ cái tiếng Việt, góc toán tư duy và rèn luyện tư thế ngồi, cầm bút đúng cách, tạo hành trang vững vàng nhất cho con bước vào Lớp 1.',
        facilityPlayCorner: 'Phòng Đồ Chơi & Vận Động Trong Nhà',
        facilityPlayCornerDesc: 'Khu vực giải trí rực rỡ sắc màu với nhà banh, cầu trượt mini và hàng trăm khối lắp ghép thông minh, nơi con giải tỏa năng lượng và rèn luyện thể chất mỗi ngày.',
        facilityFreePlay: 'Sân Chơi Tự Do Ngoài Trời',
        facilityFreePlayDesc: 'Khoảng sân thoáng mát, rợp bóng cây xanh là nơi các con cùng cô tập thể dục buổi sáng, hít thở không khí trong lành, tắm nắng và tham gia các trò chơi dân gian vui nhộn.',
        facilityOffice: 'Văn Phòng Ban Giám Hiệu & Tiếp Đón',
        facilityOfficeDesc: 'Không gian lịch sự, chu đáo là nơi nhà trường lắng nghe những tâm tư, trao đổi tình hình học tập của bé cùng phụ huynh và tiếp nhận thủ tục nhập học nhanh chóng.',

        // Nutrition & Health Section
        nutritionBadge: 'Dinh Dưỡng & Sức Khỏe',
        nutritionTitle: 'Chăm chút từng bữa ăn ngon & Giấc ngủ yên lành',
        nutritionDesc: 'Chúng tôi hiểu rằng một thể trạng khỏe mạnh chính là nền tảng vững vàng cho trí tuệ thông minh. Mỗi bữa ăn tại Nắng Hồng đều được chuẩn bị bằng tình thương của người mẹ.',
        mealScheduleTitle: 'Thời gian biểu 4 cữ ăn khoa học trong ngày',
        breakfastTitle: 'Bữa Sáng Năng Lượng (07:30 - 08:15)',
        breakfastDesc: 'Các món ăn sáng ấm nóng, dễ tiêu hóa như cháo tôm bí đỏ, phở bò tươi, nui nấu thịt bằm... giúp các con nạp đầy năng lượng khởi đầu ngày học tập hứng khởi.',
        morningSnackTitle: 'Bữa Phụ Sáng Tươi Mát (09:30 - 09:45)',
        morningSnackDesc: 'Bổ sung các loại sữa hạt nguyên chất, sữa chua thanh trùng hoặc nước ép trái cây tươi theo mùa giúp cung cấp vitamin và tăng cường đề kháng tự nhiên cho con.',
        lunchTitle: 'Bữa Trưa Trọn Vẹn Dưỡng Chất (11:00 - 11:45)',
        lunchDesc: 'Thực đơn cơm nóng gồm món mặn giàu đạm, món xào, canh rau mát lành và hoa quả tráng miệng, cân đối hoàn hảo giữa 4 nhóm chất: đường bột, đạm, béo, vitamin và khoáng chất.',
        afternoonSnackTitle: 'Bữa Xế Bồi Dưỡng Chiều (14:30 - 15:15)',
        afternoonSnackDesc: 'Sau giấc ngủ trưa sâu giấc, các con được nạp lại năng lượng với bánh flan tươi tự làm, súp gà hạt sen ấm bụng hoặc sữa chua men sống bổ dưỡng.',
        commit1Title: 'Thực Phẩm Tươi Sạch Rõ Nguồn Gốc',
        commit1Desc: 'Thịt cá tươi sống và rau củ quả được nhập mới mỗi ngày từ các nhà cung cấp uy tín đạt chứng nhận vệ sinh an toàn thực phẩm, tuyệt đối không dùng chất bảo quản hay thực phẩm đông lạnh lâu ngày.',
        commit2Title: 'Lưu Mẫu Thức Ăn Nghiêm Ngặt 24H',
        commit2Desc: 'Toàn bộ các món ăn hàng ngày đều được trích lưu mẫu trong hũ thủy tinh niêm phong, ghi rõ ngày giờ và bảo quản lạnh trong vòng 24 giờ đúng quy định nghiêm ngặt của Sở Y Tế.',
        commit3Title: 'Theo Dõi Thể Trạng & Khám Sức Khỏe',
        commit3Desc: 'Cân đo chiều cao, cân nặng định kỳ hàng tháng để theo dõi sát sao biểu đồ tăng trưởng của bé; đồng thời phối hợp cùng trạm y tế kiểm tra sức khỏe tổng quát, mắt và răng miệng cho con.',

        // Tuition Section (Gọn gàng mức 2.8tr - 3tr)
        tuitionBadge: 'Học Phí Minh Bạch',
        tuitionTitle: 'Học phí trọn gói & Đồng hành tài chính cùng ba mẹ',
        tuitionDesc: 'Nhà trường cam kết mức thu học phí hợp lý, rõ ràng và ổn định, mang đến môi trường giáo dục chất lượng mà không tạo gánh nặng kinh tế cho gia đình.',
        tuitionRangePrice: '2.800.000đ – 3.000.000đ',
        tuitionMonth: '/ tháng',

        // Map & Location
        mapBadge: 'Vị Trí & Liên Hệ',
        mapTitle: 'Kính mời quý phụ huynh ghé thăm Mầm Non Nắng Hồng',
        mapDesc: 'Không gì an tâm hơn khi chính mắt ba mẹ nhìn thấy lớp học của con và cảm nhận không khí thân thương của trường. Cánh cửa Nắng Hồng luôn rộng mở chào đón gia đình.',
        mapAddressLabel: 'Địa chỉ khuôn viên trường:',
        mapWorkingHoursLabel: 'Khung giờ đón tiếp phụ huynh:',
        mapWorkingHoursValue: 'Thứ 2 - Thứ 6: 07:00 - 17:30 | Thứ 7: 07:30 - 11:30 (Hỗ trợ đón muộn theo nhu cầu)',
        mapGetDirections: 'Xem chỉ đường trực tiếp trên Google Maps',
    },

    en: {
        brandName: 'Nang Hong Kindergarten',
        slogan: 'A joyful learning home where children thrive every day',
        // Trong khối en:
        navHome: 'Home',
        navAbout: 'About',
        navPrograms: 'Programs',
        navFacilities: 'Facilities',
        navTuition: 'Tuition',
        navNews: 'News',
        navContact: 'Contact',
        applyNow: 'Consultation & Admission',
        loadError: 'Unable to load homepage data. Please refresh your page.',
        subscribeSuccessSummary: 'Subscribed Successfully',
        subscribeSuccessDetail: 'Thank you for following and trusting Nang Hong Kindergarten.',
        errorSummary: 'Error Occurred',
        subscribeError: 'Could not complete newsletter subscription at this time.',
        applyMissingSummary: 'Incomplete Details',
        applyMissingDetail: 'Please enter parent full name, phone number, and child’s name.',
        applyMissingProgramSummary: 'Class Unselected',
        applyMissingProgramDetail: 'Please choose the appropriate age class for your child.',
        applySuccessSummary: 'Application Received',
        applySuccessDetail: 'Our school board will contact you shortly to provide detailed consultation.',
        applyError: 'Unable to send admission form now. Please try again.',
        fallbackProgramTitle1: 'Mam Class (3 Years Old) - Gentle Adaptation',
        fallbackProgramDetail1: 'First steps into group routines, learning to share toys and building early self-care habits with tender love from caring teachers.',
        fallbackProgramTitle2: 'Choi Class (4 Years Old) - Curiosity & Independence',
        fallbackProgramDetail2: 'Enhancing fine motor skills, expressive language, and social interaction through engaging hands-on play and group activities.',
        fallbackProgramTitle3: 'La Class (5 Years Old) - Confident Transition to Grade 1',
        fallbackProgramDetail3: 'Solid pre-primary preparation with language readiness, fundamental math reasoning, and positive self-confidence for primary school.',
        fallbackTeacher1: 'Ms. Nang Hong',
        fallbackTeacher2: 'Ms. Hoa Mai',
        fallbackTeacher3: 'Ms. Anh Duong',
        fallbackTeacher4: 'Ms. Bich Ngoc',
        kindergartenTeacher: 'Preschool Homeroom Teacher',
        talentTeacher: 'Music & Creative Arts Teacher',
        careTeacher: 'Childcare & Nutrition Specialist',
        classTeacher: 'Early Childhood Educator',
        programAlt: 'Preschool Curriculum',
        programFallbackDetail: 'Standard curriculum aligned with hands-on discovery, physical recreation, and comprehensive emotional intelligence.',
        viewDetail: 'View Class Details',
        teacherAlt: 'Nang Hong Kindergarten Faculty',
        heroBadge: '🌞 Nang Hong Kindergarten - Your Child’s Second Home',
        heroTitle: 'Every school day is filled with pure joy & discovery',
        heroDesc: 'Understanding that early childhood is the golden window that shapes a child’s personality and emotional well-being, Nang Hong provides an affectionate, secure, and vibrant sanctuary where every child is listened to and nurtured to grow happily.',
        admission: 'Enrollment Now',
        viewPrograms: 'Explore Classes',
        programsBadge: 'Educational Framework',
        programsTitle: 'Hands-on Learning & Practical Exploration',
        programsDesc: 'We prioritize intuitive education where learning seamlessly merges with joyful physical activity, enabling children to absorb knowledge effortlessly and naturally.',
        aboutAlt: 'About Nang Hong Kindergarten',
        aboutTitle: 'Every child is a unique seed that deserves gentle nurturing.',
        aboutDefaultQuote: 'At Nang Hong, we never impose rigid molds on young minds. Our educators are patient companions who ignite curiosity and cultivate kind, resilient, and cheerful souls.',
        yearsExperience: 'Years of Experience',
        studentsPerYear: 'Happy Children Enrolled / Year',
        achievements: 'Honors & Recognitions',
        teachersBadge: 'Our Caring Teachers',
        teachersTitle: 'Loving second mothers to every child',
        teachersDesc: '100% qualified preschool teachers who dedicate their hearts to children’s safety, wellness, and radiant daily smiles.',
        videoTitle: 'A Day at Nang Hong',
        videoDesc: 'Take a virtual tour to discover our wholesome daily moments, delicious meals, and cheerful laughter at school.',
        openVideo: 'Watch Full Video',
        noVideo: 'School introduction video is currently being updated.',
        applyBadge: 'New Academic Year Enrollment',
        applyTitle: 'Book a Consultation & Campus Tour',
        applyDescPrefix: 'Admission Period:',
        applyDescSuffix: 'We warmly welcome parents and children to visit our classrooms firsthand and consult directly with our school board.',
        openNow: 'Applications Open',
        parentName: 'Parent Full Name *',
        parentNamePlaceholder: 'e.g. John Doe',
        phone: 'Contact Phone Number *',
        phonePlaceholder: 'e.g. 0901 234 567',
        email: 'Email Address',
        emailPlaceholder: 'parent@gmail.com',
        childName: 'Child’s Full Name *',
        childNamePlaceholder: 'e.g. Baby Liam',
        childAge: 'Child’s Age',
        childAgePlaceholder: 'e.g. 3 years old (Mam Class)',
        programRequired: 'Select Desired Class *',
        selectProgram: '-- Select an appropriate class --',
        message: 'Message / Questions for the School',
        messagePlaceholder: 'Please feel free to ask about pick-up schedules, dietary options, or schedule a weekend visit...',
        submitApplication: 'Submit Registration Form',
        newsBadge: 'Campus Life & News',
        newsTitle: 'Vibrant Life at Nang Hong',
        newsDesc: 'Stay updated with seasonal festivals, classroom adventures, weekly menus, and key school announcements.',
        noContent: 'Announcements are being updated.',
        byAuthor: 'Posted by',
        readMore: 'Read Full Story',
        newsletterTitle: 'Subscribe to Nang Hong Newsletter',
        newsletterDesc: 'Get practical parenting tips, seasonal nutritional menus, and early enrollment benefits directly in your inbox.',
        newsletterPlaceholder: 'Enter your email address...',
        subscribe: 'Subscribe',
        footerDefault: 'Nang Hong Kindergarten is dedicated to being a trusted educational haven where parents place complete peace of mind during their child’s precious early years.',
        quickLinks: 'Quick Links',
        footerAbout: 'About Us',
        footerPrograms: 'Classes',
        footerNews: 'School News',
        footerContact: 'Contact',
        contactTitle: 'Admissions Office',
        defaultAddress: 'Ho Chi Minh City, Vietnam',

        // Highlights Section
        highlightsBadge: 'Core Principles',
        highlightsTitle: 'Why Parents Confidently Trust Nang Hong?',
        highlightsDesc: 'We construct an early educational foundation based on sincere love, deep respect, and seamless partnership with families.',
        highlight1Title: 'Child-Centered Philosophy',
        highlight1Desc: 'Free from academic pressure, our curriculum emphasizes discovery through direct experience, encouraging natural curiosity and early independence.',
        highlight2Title: 'Continuous 24/7 Online Camera',
        highlight2Desc: 'High-definition wide-angle camera coverage across all rooms allows parents to follow and accompany their child’s daily moments with total peace of mind.',
        highlight3Title: 'Cozy & Welcoming Atmosphere',
        highlight3Desc: 'Classrooms capture abundant natural sunlight with clean, non-slip wooden/foam floors and child-sized furniture providing family-like comfort.',
        highlight4Title: 'Balanced Nutrition & Fresh Food',
        highlight4Desc: 'Four daily meal intervals formulated according to pediatric nutrition standards, using 100% fresh, certified daily ingredients in a clean one-way kitchen.',
        highlight5Title: 'Optimal Student-Teacher Ratio',
        highlight5Desc: 'Class sizes remain deliberately moderate so teachers can intimately understand, comfort, and attend to each child’s unique pace and character.',
        highlight6Title: 'Rigorous Hygiene & Health Care',
        highlight6Desc: 'Daily morning temperature checks and thoroughly sanitized toys create a spotless, safe barrier against seasonal childhood ailments.',

        // Facilities Section
        facilitiesBadge: 'Campus & Classrooms',
        facilitiesTitle: 'Safe, Warm, and Child-Friendly Spaces',
        facilitiesDesc: 'Every corner at Nang Hong is thoughtfully arranged with premium child-proofing, encouraging active physical development and creative imagination.',
        facilityMam: 'Mam Class (3 Years Old)',
        facilityMamDesc: 'Spacious and cheerful setting equipped with soft toys and ergonomic furniture helping toddlers settle gently into group routines.',
        facilityChoi: 'Choi Class (4 Years Old)',
        facilityChoiDesc: 'Richly partitioned activity corners—role-playing, arts & crafts, and construction—boosting expressive language and peer collaboration.',
        facilityLa: 'La Class (5 Years Old)',
        facilityLaDesc: 'Tailored with alphabet literacy, foundational logic corners, and proper desk habits, confidently paving the path to Primary School.',
        facilityPlayCorner: 'Indoor Active Toy Room',
        facilityPlayCornerDesc: 'A bright, colorful wonderland with a ball pit, soft mini-slides, and educational building blocks for safe indoor energy release.',
        facilityFreePlay: 'Open Outdoor Play Yard',
        facilityFreePlayDesc: 'A shaded, airy yard where children enjoy morning gymnastics, breathe fresh air, take morning sun, and join joyful traditional games.',
        facilityOffice: 'Reception & Management Office',
        facilityOfficeDesc: 'A dedicated, welcoming consultation area where the school board attentively coordinates with parents regarding daily progress.',

        // Nutrition & Health Section
        nutritionBadge: 'Nutrition & Health',
        nutritionTitle: 'Nutritious Meals & Peaceful Afternoon Naps',
        nutritionDesc: 'Recognizing that sound health is the foundation of sharp intellect, every dish served at Nang Hong is prepared with a mother’s genuine care.',
        mealScheduleTitle: 'Scientific 4-Meal Daily Schedule',
        breakfastTitle: 'Energizing Morning Breakfast (07:30 - 08:15)',
        breakfastDesc: 'Warm, highly digestible courses such as pumpkin shrimp porridge, beef noodle soup, and minced meat pasta fueling active mornings.',
        morningSnackTitle: 'Nutrient-Rich Mid-Morning Snack (09:30 - 09:45)',
        morningSnackDesc: 'Pure organic plant milk, fresh pasteurized yogurt, or seasonal natural fruit juices boosting natural immunity and hydration.',
        lunchTitle: 'Comprehensive Wholesome Lunch (11:00 - 11:45)',
        lunchDesc: 'Hot meal combining protein, fresh greens, balanced soup, and fresh fruits, delivering all 4 essential food nutrient groups.',
        afternoonSnackTitle: 'Rejuvenating Afternoon Snack (14:30 - 15:15)',
        afternoonSnackDesc: 'Upon waking from afternoon rest, children enjoy house-made flan, lotus seed chicken soup, or probiotic yogurt for quick energy replenishment.',
        commit1Title: 'Certified Fresh & Traceable Ingredients',
        commit1Desc: 'Fresh meats and vegetables delivered fresh every morning with certified safety credentials; absolutely no harmful preservatives or stale frozen foods.',
        commit2Title: 'Strict 24-Hour Food Sample Preservation',
        commit2Desc: 'All cooked dishes are systematically sealed in sterilized glass containers, labeled, and refrigerated for 24 hours under Health Department protocols.',
        commit3Title: 'Periodic Health & Growth Milestones',
        commit3Desc: 'Monthly height and weight charts track individual growth milestones, paired with bi-annual ENT, dental, and vision screenings.',

        // Tuition Section
        tuitionBadge: 'Transparent Fees',
        tuitionTitle: 'All-Inclusive Fees & Parental Partnership',
        tuitionDesc: 'A stable, transparent, and fair tuition rate that delivers quality preschool education without posing economic burdens on families.',
        tuitionRangePrice: '2,800,000 – 3,000,000 VND',
        tuitionMonth: '/ month',

        // Map & Location
        mapBadge: 'Location & Visiting',
        mapTitle: 'We Warmly Invite You to Visit Nang Hong',
        mapDesc: 'Nothing matches seeing your child’s future classrooms with your own eyes. Our doors are always warmly open to welcome your family.',
        mapAddressLabel: 'School Campus Address:',
        mapWorkingHoursLabel: 'Visiting & Reception Hours:',
        mapWorkingHoursValue: 'Mon - Fri: 07:00 - 17:30 | Sat: 07:30 - 11:30 (Late pick-up support available upon request)',
        mapGetDirections: 'View Direct Route on Google Maps',
    }
} as const;

export type LandingLanguage = keyof typeof landingText;